### ISSUE TITLE
oauth need server side support

### ISSUE THREAD

**Issue by flufy3d** [moneybutton/api-client#1]
```
 await moneyButtonClient.handleAuthorizationResponse()

const result = await moneyButtonClient.getIdentity()

```
I will use the result to add new accout ,if all logic running in client side ,it's not safe ,hack can just pass any mb id  to cheat register.

I use vue + express ,please don't heavy rely on react.

or you can just offer some rest api logic  I can write my own plugin

**Comment by flufy3d** [comment]
I try to request login on vue client .
oauth on server

`Error: Invalid OAuth state.
    at MoneyButtonClient._handleAuthorizationCodeGrantAuthorizationResponse (/home/kenshin/daydaybsv/server/node_modules/@moneybutton/api-client/dist/moneybutton.client.cjs.js:497:15)
    at MoneyButtonClient.handleAuthorizationResponse (/home/kenshin/daydaybsv/server/node_modules/@moneybutton/api-client/dist/moneybutton.client.cjs.js:454:18)
    at router.get.asyncHandler (/home/kenshin/daydaybsv/server/routes/oauth.js:21:31)
    at asyncUtilWrap (/home/kenshin/daydaybsv/server/node_modules/express-async-handler/index.js:3:20)
    at Layer.handle [as handle_request] (/home/kenshin/daydaybsv/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/kenshin/daydaybsv/server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/kenshin/daydaybsv/server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/kenshin/daydaybsv/server/node_modules/express/lib/router/layer.js:95:5)
    at /home/kenshin/daydaybsv/server/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/kenshin/daydaybsv/server/node_modules/express/lib/router/index.js:335:12)`

**Comment by flufy3d** [comment]
btw, I don't like SSR ,I prefer local page rendering ,because my application has  complicate js and ui logic.

**Comment by ryanxcharles** [comment]
the user is redirected to a URL of your choosing with a token in the URL. you can use that token server-side. nothing has to be done client-side.

**Comment by flufy3d** [comment]
> the user is redirected to a URL of your choosing with a token in the URL. you can use that token server-side. nothing has to be done client-side.

no, I can't 


`
_doAuthorizationCodeGrantAuthorizationRequest (
      redirectUri,
      scope
    ) {
      if (this.clientSecret !== null) {
        throw new Error([
          'Grant `authentication_code` can only be performed by ',
          'a public client (that is, a client with no client secret).'
        ].join(''))
      }
      const state = uuid.v4()
      this._setRedirectUri(redirectUri)
      this._setState(state)
      const authorizationUri = [
        `${API_AUTH_URI}/oauth/v1/authorize`,
        queryString.stringify({
          response_type: 'code',
          client_id: this.clientId,
          redirect_uri: redirectUri,
          scope,
          state
        })
      ].join('?')
      this._redirectToUri(authorizationUri)
    }
`
const state = uuid.v4()

because this requestAuthorization and  handleAuthorizationResponse  should be in same side
